### ISSUE TITLE
Swift3

### ISSUE THREAD

**Issue by nsleche** [anatoliyv/RevealMenuController#1]
awesome project, it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by anatoliyv** [comment]
Hi, @nschucky. Here is [swift3 branch](https://github.com/anatoliyv/RevealMenuController/tree/swift3). Thank you for contribution!

**Comment by anatoliyv** [comment]
Now [version 0.3.0](https://github.com/anatoliyv/RevealMenuController/releases/tag/v.0.3.0) is for Swift3
